INSERT INTO review (hotel_id, user_id, rating, comment, review_date) VALUES
(1, 2, 5, 'Phòng sạch sẽ, nhân viên thân thiện và luôn hỗ trợ kịp thời. Đây là trải nghiệm tuyệt vời.', '2024-10-01'),
(1, 3, 4, 'Không gian khách sạn yên tĩnh, phù hợp để nghỉ dưỡng. Tuy nhiên, bữa sáng cần đa dạng hơn.', '2024-10-05'),
(1, 4, 3, 'Chất lượng phòng cần cải thiện, đặc biệt là nội thất đã cũ. Nhân viên thân thiện.', '2024-10-10'),
(2, 5, 4, 'Khách sạn có vị trí đẹp và dịch vụ tốt. Tuy nhiên, tôi cảm thấy giá phòng hơi cao.', '2024-10-15'),
(2, 6, 5, 'Tôi rất hài lòng với không gian rộng rãi và sự chuyên nghiệp của nhân viên.', '2024-10-20'),
(2, 2, 3, 'Phòng ốc hơi nhỏ và thiếu tiện nghi. Dịch vụ ở mức trung bình, cần cải thiện.', '2024-10-25'),
(3, 3, 4, 'Dịch vụ khách sạn ổn định, phòng sạch sẽ và thoải mái. Tuy nhiên, tiếng ồn từ hành lang khá lớn.', '2024-11-01'),
(3, 4, 5, 'Phong cảnh xung quanh khách sạn rất đẹp, không gian yên tĩnh và nhân viên tận tình.', '2024-11-05'),
(3, 6, 3, 'Tôi thấy phòng không đạt kỳ vọng, nội thất khá cũ và ánh sáng không tốt.', '2024-11-10'),
(4, 2, 4, 'Khách sạn có nhân viên thân thiện và không gian phòng sạch sẽ. Phù hợp cho gia đình.', '2024-11-15'),
(4, 5, 5, 'Dịch vụ rất chuyên nghiệp, bữa sáng ngon miệng và đa dạng. Tôi sẽ quay lại.', '2024-11-20'),
(4, 3, 3, 'Phòng không thoải mái, hơi chật chội. Bữa sáng cũng cần cải thiện thêm.', '2024-11-25'),
(5, 6, 5, 'Phong cách phục vụ chuyên nghiệp, không gian đẹp và vị trí thuận tiện cho việc đi lại.', '2024-12-01'),
(5, 2, 4, 'Khách sạn có dịch vụ ổn định và nhân viên nhiệt tình. Giá cả hợp lý.', '2024-12-05'),
(5, 4, 3, 'Tôi thấy phòng không thoáng đãng như mong đợi. Dịch vụ tạm ổn.', '2024-12-10'),
(6, 5, 4, 'Không gian thoáng đãng, thích hợp cho các chuyến đi công tác hoặc nghỉ ngơi cuối tuần.', '2024-12-15'),
(6, 3, 5, 'Tôi rất thích cách thiết kế không gian của khách sạn. Dịch vụ cũng rất chu đáo.', '2024-12-20'),
(6, 4, 3, 'Phòng cần cách âm tốt hơn vì tiếng ồn từ các phòng bên cạnh. Dịch vụ tạm ổn.', '2024-12-25'),
(7, 2, 5, 'Phong cảnh đẹp và không gian yên tĩnh. Dịch vụ rất chuyên nghiệp và tận tâm.', '2024-10-30'),
(7, 6, 4, 'Khách sạn có vị trí đẹp, gần các khu vui chơi. Tuy nhiên, nội thất cần cải thiện.', '2024-11-03'),
(7, 5, 3, 'Dịch vụ chưa thực sự tốt, đặc biệt là thời gian chờ check-in khá lâu.', '2024-11-08'),
(8, 3, 4, 'Giá cả hợp lý, phòng sạch sẽ và đội ngũ nhân viên thân thiện. Tôi rất hài lòng.', '2024-11-13'),
(8, 4, 5, 'Không gian khách sạn rộng rãi và thoải mái. Phù hợp cho cả gia đình và nhóm bạn.', '2024-11-18'),
(8, 2, 3, 'Phòng hơi cũ và dịch vụ chưa đạt kỳ vọng. Nhân viên thân thiện.', '2024-11-23'),
(9, 6, 5, 'Khách sạn mang lại cảm giác thư giãn với không gian xanh và thiết kế hiện đại.', '2024-11-28'),
(9, 2, 4, 'Dịch vụ ổn định, không gian phòng đẹp. Tuy nhiên, giá phòng hơi cao so với kỳ vọng.', '2024-12-02'),
(9, 3, 3, 'Tôi nghĩ khách sạn cần cải thiện thêm về nội thất phòng. Dịch vụ ổn định.', '2024-12-06'),
(10, 4, 5, 'Phòng được trang bị tiện nghi hiện đại và không gian thoáng đãng. Dịch vụ tuyệt vời.', '2024-12-10'),
(10, 5, 4, 'Nhân viên thân thiện, bữa sáng ngon và view đẹp. Tuy nhiên, giá hơi cao.', '2024-12-15'),
(10, 2, 3, 'Không gian phòng cần cải thiện. Tôi mong muốn dịch vụ sẽ tốt hơn.', '2024-12-20'),
(11, 6, 5, 'Không gian yên tĩnh và tiện nghi hiện đại. Tôi rất hài lòng với trải nghiệm tại đây.', '2024-12-25'),
(11, 3, 4, 'Nhân viên phục vụ tốt, dịch vụ ổn. Phù hợp cho các chuyến đi nghỉ dưỡng.', '2024-12-30'),
(11, 4, 3, 'Phòng hơi nhỏ và nội thất cũ. Khách sạn cần cải thiện thêm về tiện nghi.', '2024-12-31'),
(12, 2, 4, 'Phòng sạch sẽ và đầy đủ tiện nghi. Nhân viên phục vụ chu đáo và nhiệt tình.', '2024-10-20'),
(12, 5, 5, 'Tôi rất hài lòng với không gian thoáng đãng và dịch vụ tuyệt vời của khách sạn.', '2024-10-25'),
(12, 3, 3, 'Dịch vụ bữa sáng không đa dạng. Phòng ở cần được nâng cấp.', '2024-10-30'),
(13, 6, 5, 'Không gian xanh mát, vị trí thuận tiện và dịch vụ hoàn hảo. Đây là nơi lý tưởng.', '2024-11-01'),
(13, 4, 4, 'Nhân viên thân thiện, bữa sáng ngon và không gian phòng thoải mái.', '2024-11-05'),
(13, 2, 3, 'Dịch vụ cần cải thiện, đặc biệt là chất lượng phòng. Giá phòng hơi cao.', '2024-11-10'),
(14, 5, 4, 'Không gian phòng sạch sẽ, bữa sáng ngon miệng. Nhân viên phục vụ tận tình.', '2024-11-15'),
(14, 3, 5, 'Tôi rất ấn tượng với không gian thoáng đãng và tiện nghi hiện đại tại khách sạn.', '2024-11-20'),
(14, 6, 3, 'Phòng ốc cần nâng cấp, dịch vụ không ổn định. Tôi chưa hài lòng.', '2024-11-25');

INSERT INTO review_rental (rental_id, user_id, rating, comment, review_date) VALUES
(1, 2, 5, 'Xe rất tốt, sạch sẽ và thoải mái. Tôi cảm thấy rất hài lòng khi sử dụng dịch vụ này và sẽ giới thiệu cho bạn bè.', '2024-12-01'),
(1, 3, 4, 'Dịch vụ khá tốt nhưng giá thuê xe có phần hơi cao so với kỳ vọng. Tuy nhiên, trải nghiệm tổng thể vẫn ổn.', '2024-12-03'),
(1, 4, 5, 'Rất hài lòng với chất lượng xe cũng như thái độ phục vụ của nhân viên. Chắc chắn tôi sẽ thuê lại lần sau.', '2024-12-05'),
(2, 2, 4, 'Xe chạy ổn định, phù hợp cho những chuyến đi ngắn ngày. Tuy nhiên, tôi mong muốn có thêm nhiều tùy chọn hơn.', '2024-12-02'),
(2, 3, 5, 'Dịch vụ rất chuyên nghiệp, xe mới và sạch sẽ. Tôi cảm thấy yên tâm khi sử dụng dịch vụ tại đây.', '2024-12-04'),
(2, 5, 4, 'Chuyến đi khá ổn, giá cả hợp lý. Tôi nghĩ rằng công ty nên cải thiện thêm về thời gian giao xe.', '2024-12-06'),
(3, 2, 3, 'Xe hoạt động tốt nhưng có một số vấn đề nhỏ về bảo trì. Hy vọng dịch vụ sẽ cải thiện hơn trong tương lai.', '2024-12-03'),
(3, 4, 4, 'Tạm ổn, dịch vụ cần được cải thiện thêm. Tuy nhiên, nhân viên rất nhiệt tình và hỗ trợ tốt.', '2024-12-05'),
(3, 5, 5, 'Rất hài lòng với trải nghiệm thuê xe tại đây. Xe mới, chạy êm và mọi thứ đều rất chuyên nghiệp.', '2024-12-07'),
(4, 3, 5, 'Xe mới, trải nghiệm chuyến đi rất tuyệt vời. Tôi hoàn toàn hài lòng với chất lượng dịch vụ của công ty.', '2024-12-01'),
(4, 4, 4, 'Giá hơi cao hơn mong đợi nhưng chất lượng dịch vụ rất tốt. Tôi sẽ cân nhắc thuê lại.', '2024-12-04'),
(4, 5, 5, 'Xe chất lượng, giá cả hợp lý. Tôi sẽ giới thiệu cho bạn bè nếu họ cần thuê xe.', '2024-12-06'),
(5, 2, 4, 'Dịch vụ khá tốt, tuy nhiên xe có một chút mùi lạ. Tổng thể thì tôi vẫn thấy hài lòng với chuyến đi.', '2024-12-02'),
(5, 3, 3, 'Xe ổn nhưng điều hòa hoạt động không được mạnh. Tôi mong rằng công ty sẽ cải thiện vấn đề này.', '2024-12-05'),
(5, 6, 5, 'Xe rất tốt, nhân viên phục vụ nhiệt tình và chuyên nghiệp. Tôi sẽ quay lại trong lần thuê xe tới.', '2024-12-07'),
(6, 4, 5, 'Chuyến đi rất thoải mái. Xe mới, nội thất đẹp và nhân viên giao xe rất đúng giờ. Tôi rất hài lòng.', '2024-12-03'),
(6, 5, 4, 'Xe tốt nhưng tôi nghĩ công ty nên bổ sung thêm các dòng xe khác để có nhiều sự lựa chọn hơn.', '2024-12-06'),
(6, 6, 5, 'Rất tốt, xe chất lượng cao và dịch vụ rất chuyên nghiệp. Tôi hoàn toàn yên tâm khi thuê xe tại đây.', '2024-12-08'),
(7, 3, 4, 'Xe tốt nhưng thời gian giao xe hơi trễ. Nhân viên nhiệt tình nhưng cần cải thiện khâu giao nhận xe.', '2024-12-01'),
(7, 5, 5, 'Trải nghiệm thuê xe rất tuyệt vời. Tôi cảm thấy rất thoải mái và xe chạy rất êm. Giá cả cũng hợp lý.', '2024-12-04'),
(7, 6, 5, 'Dịch vụ chuyên nghiệp, nhân viên thân thiện và hỗ trợ tận tình. Tôi sẽ quay lại lần sau.', '2024-12-07'),
(8, 2, 3, 'Xe tạm ổn nhưng không để lại nhiều ấn tượng. Dịch vụ ở mức trung bình, cần cải thiện hơn.', '2024-12-02'),
(8, 4, 4, 'Giá cả hợp lý, dịch vụ tốt và nhân viên rất nhiệt tình. Tôi hài lòng với trải nghiệm tại đây.', '2024-12-05'),
(8, 6, 5, 'Dịch vụ rất tuyệt vời, xe mới và sạch sẽ. Tôi chắc chắn sẽ giới thiệu công ty này cho bạn bè.', '2024-12-08'),
(9, 3, 4, 'Xe ổn nhưng thời gian giao xe hơi lâu. Dịch vụ hỗ trợ khách hàng tốt và thân thiện.', '2024-12-03'),
(9, 4, 5, 'Xe mới và dịch vụ rất tốt. Tôi cảm thấy rất hài lòng và sẽ thuê lại nếu có dịp.', '2024-12-06'),
(9, 6, 5, 'Chất lượng xe rất tốt, trải nghiệm dịch vụ rất tuyệt vời. Tôi đánh giá cao công ty này.', '2024-12-09');